* [32mdevelopment[m
  feature/authentication[m
  feature/dark-mode[m
  feature/movie-details[m
  feature/movie-list[m
  feature/pagination[m
  feature/reviews[m
  feature/search-filter[m
  feature/setup-project[m
  feature/state-management[m
  feature/ui-polish[m
  feature/watchlist[m
  fix/api-errors[m
  fix/auth-redirect[m
  fix/darkmode[m
  fix/deployment[m
  fix/ui-bugs[m
  main[m
  ui/header-section[m
